language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - sprinteiro@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=35.176.155.132
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
- sh travis_scripts/trigger_platform_tests.sh
env:
  global:
  - secure: bms2AKQiRPH+98JF5UY0+Q3JMvTPTFMipL8Z2oitOTRMh6UIr3IEaTth14BKxpc35k5L/l5ohGowARa44LWcxNB1ifPiS0Ihj5eBe8clAtTvLYhjs6Zcf5OXIEZbWVyxS4qyVPVLsxTJS+xmkTGTGICojrxpodYmf8l0ivv6ZloxraxcQJ/woBjQRrQt35brQSOJ6KcILi2CI3hx+IsVQ32ClYPMPN55NR+8qfEAEVqYZCguhwmtP0fELqsD/tCtE3di6nN2BGHtM/yenkJG/n1m7HZbJxqIqShv0PCBoZgRjsgAxOJpN132OL4bB0vQG06H3pegDIRiM2GdxwYDFzcrynEQhbe37Sx51DdAtpDt/QXZHKA7puhApYMH7OnMAlte7xzWrfWt48pColWuFHjynDT1B2lxzBTH5b5p8AgBUcWT4N88o0DAG8O5UpBYETFPD0A2tHDG5ZMmCVjg3AcBDcAwIl80XayksbpgePwOaaF/3AbBaxdHaTcJ2RGHpZLhSlNeH35aEroxr1EVkZyujH8ra1miTHoK/6jg+2z6YjYjeaGsO9a+qx8mnX1tCY7zKQ+9RurfU00r9rs74QmQNODsOltUqaorqHU1fOmN45jOU41ZmkK5cb12oOiRfD63nip4e+F4L9ZU1ljFSbPvfnrYFjEP21TAFD2aFSc=
  - secure: mQqVceoW72wMeykJtTPABTfFjPTit7XA6LzVMRie9ayQcZ4lZHynds2k0OG+uFrZ8pCpTJLjgUgiY8Yg6bGHteWvMvmEawnWp/H314MBQoTU1Kh/Ygpa7qxqvkjtV0Ul0yEUs2Or7WBYxNX7GPNf6D3Qg0Ae9ZO/A5lmqBFndY9JLMNe2md5v70mcFN4xSAfPwdcvRKokm7KEdNApmerhqzh7m7acsNwlwpHYiuj1mIDQKHFlw8hBIivS5x2JMzeJE3AtCCpE7eDijmeYGznWzFQwsaaAAkfYjrId9tZdKUzL2P6GbSAxGGkHo008g+d0OeyVG5rdCwvKCP+1a4azcLud/ig4+GEpM/gaajaVk8HCqU60pZukgaqSzjUYO0xrFWGYq4V1qsuyZYhayqyjt5AAxoOVhHfeGx/yuiQ3E+X4hr4YpeKNrYPCiL1ueuCTaZu1BvpACH8G0B7qO2AqTwqWVd7IlhNzGALxctfOH2ab/X85FRf2gSwFqoCVFOo0y+nMiTlUhW+2BpoJKuiXBkMu5JTo/682cVW8vsEWv2kAvjVVZy+HbEJo4pfPAQEW3YHQX7vKvi7iaX6LNh4GW56afN4sFsVFRimeWxS6G9caEQzqVVRigS8kpRFyyNM5g9rYaSCiDFlDkewgwN+b9wyyuqI/22mNglEtrGM9UI=
  - secure: LvKV5Dgec9JCR7X9BEScxnYpYZ3uNGlM3d+WYH7ByqA1npf9bY93hBaG8nna1plzkh3z95jXQHLS+EKV7e5QBW6x7XeqflsCn66rlMkHRWdZ8Y/Rtq0VKq+7Y3j8kKT4AMLRwzj9bYbniujaTa7xphnnMC7uw74FJAMrC/aJ4vIZbNlazFH+jN8tc42CO7KK+4ooafSsoK5b4lFvaq55CCwkqwNKF0y+nbMkP+m7AK8np+0i/z/NWp9eejBszHfw1OHKdjziIrNPAyUR/MgyfJdRGTdUzcPg1Evx3yRyZ6DKp5oO7isj1Wae0SF8fqwnRKoMSaUHofzFZpLqkoC13CV4B9UTi588pkcwvbBEjGX2+33XDWyw84YzIl/NyE5u2mPIYzV+/Cy8IZrDw3NI8nir8P5GxUK1H2HkWW+Y5aR1JZ8Sgdo7QfnG0GOE5HiM7+B0jl2Mztgrfr/2MPxRG/XecPMjn0hYY9P/2J1YovE2JBaVKibE+WHogxZq5Rle7MB3dph5dv54dq0kevgrA6rsgpfgUAMiB9idwdNHPK9nKkCE1qY6Ct2wzQKBi/R1AZySqqxbofmC7RJnrSz07QVrwfZvP+xwpjuGdMICJRs29DQ9vIcnyBum5ftxu5Czht+aA4SMN1F+8SS3OM0VxA3pgdqNJ+chCnm+s/Wjfgk=
  - secure: Vj0KzB7WbR85lUWbX0l4WxiAR75qrjtf2EqWReTU9dWSmfSbXZ6IRZAZeIK3craELG6eyLOGkr83yvivL0D1Wq3RtOJkSBPdJ27kpA3d37Q/jlZbeTrSAjFyaBPbUrJ7Bke/hfIxGqTeuw68JyKQ1fRTW57wxVHKsEnn9Fo31FzE25GS2m7aT7yLcFVRM6DUIEvypB6hPJX0YxGbpSgMXUZiAABkoZP7BsdvhCu/Oag2AdioMuw3FNdPZZKR3lHNC7h27HnSYgWpgRHE4xq/Mvi7CfHSsepE+IPMDUSLwJaBnu7C/bPFHLcO1RcYkYWrLU/InTA9o64m5fBw4sLHvLlITij4NHqSAyfcfQyeAG6C1WHra8PpB6L4sROQIP4E1iZGr/mz0YCoEmrzq6ftG2qMJSPG2+mtxteLCAoTKw6NUjyEhJgER08ZGTrFpzWMXEPBPjtqc/LfJqfSfJdiLeoLybZLqhnV+BNpxASyBDm+OwAdZYY9ExqOBm+/4PL7Wqyq+xYzNltr8O69GR8+39W90DvmxpAfQ20pBBRkhZeM32Bnsj6JqFq7zkwPdvaeQNIAe7LpxkD4Aioq6Oi9alefs6iqvoethncf63jszHLeOxfedNy6kzircMKgWyKAOD+SEOKaEorAvUwvH8NACCM/lp/B29hPTwUStPzthGQ=
  - secure: Ltbsm0zZTPq1KGmqgI0EEl5sqXDbbNyC1NxzQa8v51a+d3ZqtLX+HEY0KV6BsFTjHkdYpXVFzejwMm5MRGReFPHLGQ7XSWWdwTEHeMqxNqDQqe3Nq+Q6P13jBuhaERXPtpQrpoNYc6w8RddoCOsX7L28QmyrlysPpnpkza6sFF7+l+Ect5rQwd8ZPGwmWomXVleX6VM0x56NO9kzJkEPeaKSV2r3tOcWP3BSviQZNQCvvS7nfmqXRWvqdzkolQk15nfDiIMkOeHc6fSy7Hg1PaDhb/E2Ddd2iGZv/iZoC2QTRMNt9AOz+cc0utNUKstsVt+iEbnl3v/OpjErr3k0PBWPA7y4K2fikv8WWDksXNHufvXjp/N8O2IwegVpfiPBe8kmSau5dc2JVzalSpn1OQOrKqrTmKo62oxT4We0y8WbOs/w4kjRo+pjF8VVysb5DvUWCh0iGH10eywh7qQm9A4pBdr0q/xlayftfaF8gauOmo9S3tsvnS/DorMaOt9cGchddSd9bzsOy9B98T+pwQw4ya+DQoKjdsZ+QSG9Vd0XapI08N1OIaAhDUCKyC4PFL1PAoa9e2n7F0BGulwHpeXxI3GLDJeW+6ZZHY1iKdYtjY5OHFKD6/odI3lVTa/wKaBz8Cp5QReVV/Xp3goXC6AR7D9f+r1Z8OckQHxJujU=
